sudo: required
language: java

jdk:
  - openjdk8

script:
  - ./gradlew build -x test

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \\;
    - cd /home/travis/build/build-test-conflicts/spring-boot/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true
